### ISSUE TITLE
Silent error on non-existent repo id

### ISSUE THREAD

**Issue by kierarad** [gocd-contrib/gocd-cli#20]

**Comment by marques-work** [comment]
As a larger issue, I think the `api.Request.Send()` should handle errors differently. Much like promises in JS, perhaps we should have separate success and error handlers for `Send()`, rather than a single handler for the response?

That way, we implicitly branch on `response.IsError()`. Typically, we would handle success and failures very differently, so it makes sense to have targeted handlers for each to separate concerns.

**Comment by marques-work** [comment]
Commit 68da4ec implements separate handlers for success and error responses.

**Comment by marques-work** [comment]
In the error handler, let's add a 404 check and `DieLoudly()` with a message like `No such config-repo with id: ____`
